### ISSUE TITLE
Numpy update - deprecated names

### ISSUE THREAD

**Issue by johnpatramanis** [dekoning-lab/slim-tree#65]
When using -w False -fc False options, some python scripts are called.
Newer versions of numpy however have changed how they name things a bit, so the scritps need to be updated in order for slim tree to run with the current versions of numpy.

I've encountered two occurances of this:

**slim-tree/contactmaps/utils.py", line 93, in residue_array;
a = numpy.zeros(count_residues(chain), numpy.object)**

where numpy.object needs to change to numpy.object_

and 

**/slim-tree/contactmaps/ContactMap.py, , line 32, in calc_matrix**

where numpy.bool needs to change to numpy.bool_

**Comment by ebrintn** [comment]
Closing for now as in protein contact maps which have been removed
