### ISSUE TITLE
WE NEED UNIT TESTS!!!

### ISSUE THREAD

**Issue by ebrintn** [dekoning-lab/slim-tree#72]
Every change I'm making is breaking something and finding what is broken is very very difficult to debug. Unit tests need to be made or I am going to be pulling my hair out!

**Comment by Adelanao** [comment]
we managed our self business we are security guard company

**Comment by Adelanao** [comment]
I need your help your financially

**Comment by ebrintn** [comment]
Unit tests finished with final push to redev. Just looking for final bugs by running examples.

**Comment by ebrintn** [comment]
Unit tests finished
