### ISSUE TITLE
R script crashes when codon_stationary_distribution has only one column

### ISSUE THREAD

**Issue by jasondk** [dekoning-lab/slim-tree#90]
Duplicating the single column fixed it for me

**Comment by jasondk** [comment]
In `utils/fitness_profile_finder.R`, it crashes on:

Error in colSums(freqs[, -ncol(freqs)]) : 
'x' must be an array of at least two dimensions

**Comment by jasondk** [comment]
To reproduce the error: `python3 SLiMTree.py -n 100 -v 0.0000025 -b 10 -r 0 -g 1 -k 100 simple-tree.txt codons4.csv -f start.fasta.txt`
[codons3.csv](https://github.com/dekoning-lab/slim-tree/files/14745863/codons3.csv)
[simple-tree.txt](https://github.com/dekoning-lab/slim-tree/files/14745871/simple-tree.txt)
[start.fasta.txt](https://github.com/dekoning-lab/slim-tree/files/14745875/start.fasta.txt)

**Comment by ebrintn** [comment]
I think I fixed this with the most recent additions to unit tests
