### ISSUE TITLE
Missing documentation and examples throughout

### ISSUE THREAD

**Issue by jasondk** [dekoning-lab/slim-tree#91]
Things that are missing:
* an example `codon_stationary_distribution` file, and an example `aa_fitness_distribution` (In general, if there is an option to use a file, we must have an example and a description of the expected format of the file)
* instructions for the user to install all python3 and R dependencies
* some example command-lines to run in the README

**Comment by jasondk** [comment]
* Also, when trying to do a single locus simuation (`-g 1` codon) - an error is generated saying that the genome length must be the same as the number of fitness profiles given. Since I was forced to give a minimum of 2 fitness profiles, i am forced to have a minimum genome size of 2 codons. Should allow the user to do a 1 codon genome
Error message: `Please ensure that when using a fasta file, the same number of fitness profiles are provided as the length of the genome in the fasta file. Exiting.`
* In the help system, it says the starting sequence file should be in amino-acids. When this is provided, an error is generated saying that nucleotides are required

**Comment by ebrintn** [comment]
Done
